version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-testdock
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5433:5432'
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  project2:
    image: project2
    restart: always
    container_name: project2-test
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
    depends_on:
      - postgres
    networks:
      - my-network
volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge