server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: /db/changelog.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

errorDetails:
  user-not-found:
    code: "USER_NOT_FOUND"
    message: "User not found."
    httpCode: 404
  incorrect-user:
    code: "INCORRECT_USER"
    message: "The user is invalid."
    httpCode: 400
  id-not-correct:
    code: "ID_NOT_CORRECT"
    message: "The not correct"
    http-code: 400
  default:
    code: "UNKNOWN ERROR"
    message: "The error is unknown."
    httpCode: 500

